// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPBKyeIgACkHuVb6sjlZaVS2YyGn97xQQ',
    appId: '1:480309852338:web:732363651026876e70f1ab',
    messagingSenderId: '480309852338',
    projectId: 'mediacite-app',
    authDomain: 'mediacite-app.firebaseapp.com',
    storageBucket: 'mediacite-app.firebasestorage.app',
    measurementId: 'G-REVP9BCD9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmP9AQGbEKlQm4YbMXcjZL0icG_2sxaos',
    appId: '1:480309852338:android:f0bcb14a052b8fd870f1ab',
    messagingSenderId: '480309852338',
    projectId: 'mediacite-app',
    storageBucket: 'mediacite-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKYmVFWKRQkLyZNIqXbUxdDQuV4T4NmkM',
    appId: '1:480309852338:ios:9423a392c9e2faf570f1ab',
    messagingSenderId: '480309852338',
    projectId: 'mediacite-app',
    storageBucket: 'mediacite-app.firebasestorage.app',
    iosBundleId: 'com.example.mediaciteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKYmVFWKRQkLyZNIqXbUxdDQuV4T4NmkM',
    appId: '1:480309852338:ios:9423a392c9e2faf570f1ab',
    messagingSenderId: '480309852338',
    projectId: 'mediacite-app',
    storageBucket: 'mediacite-app.firebasestorage.app',
    iosBundleId: 'com.example.mediaciteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPBKyeIgACkHuVb6sjlZaVS2YyGn97xQQ',
    appId: '1:480309852338:web:be15d8e4c756806a70f1ab',
    messagingSenderId: '480309852338',
    projectId: 'mediacite-app',
    authDomain: 'mediacite-app.firebaseapp.com',
    storageBucket: 'mediacite-app.firebasestorage.app',
    measurementId: 'G-WHLPEQGN0R',
  );
}
